# Se ejecute automÃ¡ticamente todos los dÃ­as a las 09:00 (hora UTC).

# Tenga dos pasos dentro de un job llamado daily_job:

# Paso 1: Imprima el mensaje "Buenos dÃ­as â˜€ï¸ hoy es $(date)".

# Paso 2: Solo los domingos (0 en cron), imprima "Hoy es domingo, toca descanso ðŸ›Œ".
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 9 * * *'
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener dÃ­a de la semana
        id: day
        run: echo "day=$(date +%a)" >> GITHUB_OUTPUT

      - name: Se ejecuta solo el domingo
        if: steps.day.outputs.day == 'Sun'
        run: echo "Hoy es domingo, toca descanso ðŸ›Œ"
      
      - name: Siempre se Ejecuta
        run: echo "Buenos dias hoy es $(date)"